[package]
name = "passkey-tpm-cli"
description = "passkey-tpm command line administration tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "passkey-tpm"
path = "src/main.rs"

[dependencies]
passkey-tpm-tpm = { path = "../tpm" }
passkey-tpm-wire = { path = "../wire" }
tss-esapi = "7.7"
passkey-tpm-uv = { path = "../uv" }
zbus = { version = "5.19", default-features = false, features = ["tokio"] }
tokio = { version = "1.53", features = ["rt"] }

[dev-dependencies]
passkey-tpm-testkit = { path = "../testkit" }
passkey-tpm-uvd = { path = "../uvd" }
tokio = { version = "1.53", features = ["rt", "macros", "time"] }

[lints]
workspace = true
