[package]
name = "passkey-tpm-transport-uhid"
description = "Virtual FIDO HID (uhid) transport for passkey-tpm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
